page_title: LF Builds
copier_project: lincc-frameworks/python-project-template

repos:  
  - repo: 25176-ko-server
    owner: nexusstudios
    smoke-test: ci.yml
    live-build: cd.yml
    live-build-branch: dev
  - repo: 25176-ko-cxs
    owner: nexusstudios
    smoke-test: ci.yml
    live-build: cd.yml
    live-build-branch: dev
  - repo: knockout
    display_name: "Knockout Core Product"
    owner: facebookexternal
    live-build: build-apk.yml
    live-build-branch: release-product
  - repo: knockout
    display_name: "Knockout Demo"
    owner: facebookexternal
    live-build: build-demo-apk.yml
    live-build-branch: release-demo
  - repo: knockout
    display_name: "Knockout Demo NFL"
    owner: facebookexternal
    live-build: build-demo-nfl-apk.yml
    live-build-branch: release-demo-nfl
  - repo: knockout
    display_name: "Knockout Demo MLB"
    owner: facebookexternal
    live-build: build-demo-mlb-apk.yml
    live-build-branch: release-demo-mlb