page_title: LF Builds
copier_project: lincc-frameworks/python-project-template

repos:  
  - repo: 25176-ko-server
    owner: nexusstudios
    smoke-test: ci.yml
    live-build: cd.yml
  - repo: 25176-ko-cxs
    smoke-test: ci.yml
    live-build: cd.yml
    owner: nexusstudios
  - repo: knockout Core Product
    live-build: build-apk.yml
    owner: facebookexternal
  - repo: knockout Demo
    live-build: build-demo-apk.yml
    owner: facebookexternal
  - repo: knockout Demo NFL
    live-build: build-demo-nfl-apk.yml
    owner: facebookexternal
  - repo: knockout NBA
    live-build: build-demo-nba-apk.yml
    owner: facebookexternal