page_title: LF Builds
copier_project: lincc-frameworks/python-project-template

repos:  
  - repo: 25176-ko-server
    owner: nexusstudios
  - repo: 25176-ko-cxs
    owner: nexusstudios
  - repo: knockout
    owner: facebookexternal