page_title: LF Builds
copier_project: lincc-frameworks/python-project-template

repos:  
  - repo: 25176-ko-server
    owner: nexusstudios
    smoke-test: ci.yml
    live-build: cd.yml
  - repo: 25176-ko-cxs
    smoke-test: ci.yml
    live-build: cd.yml
    owner: nexusstudios
  - repo: knockout
    smoke-test: build-demo-apk.yml
    live-build: build-demo-apk.yml
    owner: facebookexternal